name: lecture_2_2
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^2.0.0
  bloc: ^2.0.0
  dio: ^3.0.6
  geolocator: ^5.1.5
  latlong: ^0.6.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true